import mongoose from 'mongoose';
import Item from '../Modals/itemModal.js';
import { MONGO_URI } from '../Config/db.js';

/**
 * 100% vegetarian (no chicken/meat/fish/egg). Images: Unsplash photos with a more home-style / natural look.
 * Categories match frontend: breakfast, lunch, dinner, mexican, italian, desserts, drinks
 */

const retiredNames = [];

/** Remove old non-veg / egg dishes from DB so they do not still appear after re-seed */

const menuItems = [
    // —— Breakfast —— (egg-free)
    {
        name: 'Ghee Roast Masala Dosa',
        description: 'Crisp dosa with spiced potato masala, sambar, and coconut chutney.',
        category: 'breakfast',
        price: 219,
        rating: 4.7,
        hearts: 124,
        total: 219,
        imageUrl: 'https://shrisangeethasrestaurant.com/cdn/shop/files/GheeRoast.webp?v=1743704914',
    },
    {
        name: 'Berry Maple Pancake Stack',
        description: 'Fluffy pancakes with maple syrup, fresh berries — homestyle stack.',
        category: 'breakfast',
        price: 199,
        rating: 4.5,
        hearts: 98,
        total: 199,
        imageUrl: 'https://img.freepik.com/premium-photo/pancakes-with-berries-maple-syrup-sweet-homemade-stack-pancakes_157947-2438.jpg',
    },
    {
        name: 'Avocado Multigrain Toast',
        description: 'Smashed avocado, cherry tomatoes, chili flakes, and lemon on toasted multigrain.',
        category: 'breakfast',
        price: 229,
        rating: 3.5,
        hearts: 67,
        total: 229,
        imageUrl: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2015/12/11/0/FNK_All-the-Avocado-Toast_s4x3.jpg.rend.hgtvcom.1280.1280.suffix/1450059496131.webp',
    },
    {
        name: 'South Indian Breakfast Platter',
        description: 'Mini idli, medu vada, sambar, coconut chutney — shared-platter feel.',
        category: 'breakfast',
        price: 249,
        rating: 4.6,
        hearts: 110,
        total: 249,
        imageUrl: 'https://assets.gqindia.com/photos/5edf9ea70f82d6d3cee5f0b1/16:9/w_2560%2Cc_limit/5-delicious-South-Indian-breakfast-recipes-that-you-can-easily-make-at-home.jpg',
    },
    {
        name: 'Strawberry Smoothie Bowl',
        description: 'Thick blended berries, granola, banana, and chia — bright morning bowl.',
        category: 'breakfast',
        price: 219,
        rating: 4.2,
        hearts: 76,
        total: 219,
        imageUrl: 'https://www.bakeandbacon.com/wp-content/uploads/2024/08/strawberry-smoothie-bowl-featured-image.jpg',
    },
    {
        name: 'Masala Paratha & Dahi',
        description: 'Layered paratha with spiced potato filling, tempered yogurt, and pickle.',
        category: 'breakfast',
        price: 189,
        rating: 4.4,
        hearts: 89,
        total: 189,
        imageUrl: 'https://i0.wp.com/swatisani.net/kitchen/wp-content/uploads/2025/03/Mooli-Paratha.jpg?fit=1365%2C1024&ssl=1',
    },
    {
        name: 'Jaggery Oats with Seasonal Fruits',
        description: 'Slow-cooked oats with jaggery, cinnamon, banana, and toasted nuts.',
        category: 'breakfast',
        price: 169,
        rating: 4.1,
        hearts: 64,
        total: 169,
        imageUrl: 'https://i0.wp.com/pistachiodoughnut.com/wp-content/uploads/2021/01/IMG_0955_jpg.jpg?fit=574%2C640&ssl=1',
    },
    {
        name: 'Hearty Veggie Brunch Plate',
        description: 'Baked beans, herbed mushrooms, potato rosti, grilled tomato, and wholemeal toast.',
        category: 'breakfast',
        price: 319,
        rating: 4.3,
        hearts: 72,
        total: 319,
        imageUrl: 'https://images.unsplash.com/photo-1493770348161-369560ae357d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=85',
    },
    
    {
        name: 'Sabudana Khichdi',
        description: 'Light and tasty tapioca pearls cooked with peanuts and mild spices.',
        category: 'breakfast',
        price: 169,
        rating: 4.0,
        hearts: 58,
        total: 169,
        imageUrl: 'https://t4.ftcdn.net/jpg/15/88/31/45/360_F_1588314533_LVhyEnVUnaSQSsthJnfgY0PvND9qdUHG.jpg',
    },
    {
        name: 'Vegetable Poha',
        description: 'Flattened rice cooked with fresh vegetables, peanuts, and turmeric.',
        category: 'breakfast',
        price: 149,
        rating: 4.3,
        hearts: 93,
        total: 149,
        imageUrl: 'https://www.nehascookbook.com/wp-content/uploads/2022/09/Vegetable-poha-WS-1.jpg',
    },
    {
        name: 'Rava Dosa',
        description: 'Crispy semolina dosa served with chutney and sambar.',
        category: 'breakfast',
        price: 189,
        rating: 4.2,
        hearts: 87,
        total: 189,
        imageUrl: 'https://www.vegrecipesofindia.com/wp-content/uploads/2018/09/rava-dosa-recipe-1.jpg',
    },
    {
        name: 'Vegetable Sandwich',
        description: 'Fresh veggies layered in bread with butter and green chutney.',
        category: 'breakfast',
        price: 159,
        rating: 3.9,
        hearts: 61,
        total: 159,
        imageUrl: 'https://images.unsplash.com/photo-1550507992-eb63ffee0847?auto=format&fit=crop&w=1200&q=85',
    },
    {
        name: 'Methi Thepla with Pickle',
        description: 'Gujarati style methi thepla served with pickle and curd.',
        category: 'breakfast',
        price: 179,
        rating: 4.4,
        hearts: 95,
        total: 179,
        imageUrl: 'https://aplateofhappiness.net/wp-content/uploads/2023/10/img_6165-2.jpg?w=1024',
    },
    {
        name: 'Khaman Dhokla',
        description: 'Soft and spongy steamed gram flour snack with mustard tempering.',
        category: 'breakfast',
        price: 129,
        rating: 4.6,
        hearts: 130,
        total: 129,
        imageUrl: 'https://t4.ftcdn.net/jpg/10/41/99/53/360_F_1041995329_Y948A29Hru2TXn8JgkWMwJmIVauyQ9jq.jpg',
    },
    {
        name: 'Vegetable Uttapam',
        description: 'Thick dosa topped with onions, tomatoes, and capsicum.',
        category: 'breakfast',
        price: 199,
        rating: 4.1,
        hearts: 78,
        total: 199,
        imageUrl: 'https://www.yummyfoodrecipes.com/resources/picture/org/Ragi-and-Oats-Uttapam.jpg',
    },
    {
        name: 'Moong Dal Chilla',
        description: 'Healthy lentil pancakes served with chutney.',
        category: 'breakfast',
        price: 169,
        rating: 4.0,
        hearts: 69,
        total: 169,
        imageUrl: 'https://www.vegrecipesofindia.com/wp-content/uploads/2016/11/moong-dal-chilla-3u.jpg',
    },
    {
        name: 'Fruit Salad Bowl',
        description: 'Fresh seasonal fruits served chilled with a hint of honey.',
        category: 'breakfast',
        price: 149,
        rating: 3.8,
        hearts: 55,
        total: 149,
        imageUrl: 'https://www.shelovesbiscotti.com/wp-content/uploads/2020/06/Healthy-Fruit-Salad-Recipe-5.jpg',
    },
    
    {
        name: 'Plain Idli',
        description: 'Soft steamed rice cakes served with chutney and sambar.',
        category: 'breakfast',
        price: 119,
        rating: 4.2,
        hearts: 88,
        total: 119,
        imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=1200&q=85',
    },
    {
        name: 'Butter Toast',
        description: 'Crispy toasted bread served with melted butter.',
        category: 'breakfast',
        price: 99,
        rating: 3.0,
        hearts: 40,
        total: 99,
        imageUrl: 'https://img.freepik.com/free-photo/sliced-fresh-bread-butter-wooden-table_123827-35860.jpg?semt=ais_incoming&w=740&q=80',
    },
    {
        name: 'Jam Bread',
        description: 'Soft bread slices spread with sweet fruit jam.',
        category: 'breakfast',
        price: 89,
        rating: 3.5,
        hearts: 46,
        total: 89,
        imageUrl: 'https://static.vecteezy.com/system/resources/thumbnails/068/436/689/small/close-up-of-bread-slice-with-jam-photo.jpeg',
    },
    {
        name: 'Plain Paratha',
        description: 'Simple layered wheat paratha served with butter.',
        category: 'breakfast',
        price: 119,
        rating: 4.0,
        hearts: 83,
        total: 119,
        imageUrl: 'https://hotelmeera.peclick.com/uploads/1695/25/05/1605251747387333682703c598ac2.webp',
    },
    {
        name: 'Bread Butter & Sugar',
        description: 'Toasted bread with butter and a light sprinkle of sugar.',
        category: 'breakfast',
        price: 79,
        rating: 3.6,
        hearts: 34,
        total: 79,
        imageUrl: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&w=1200&q=85',
    },
    {
        name: 'Curd Rice',
        description: 'Soft rice mixed with fresh curd and mild tempering.',
        category: 'breakfast',
        price: 149,
        rating: 3.3,
        hearts: 68,
        total: 149,
        imageUrl: 'https://www.whiskaffair.com/wp-content/uploads/2014/08/Curd-Rice-2-3.jpg',
    },
    
   
    {
        name: 'Cornflakes with Milk',
        description: 'Classic cornflakes served with chilled milk.',
        category: 'breakfast',
        price: 119,
        rating: 3.9,
        hearts: 55,
        total: 119,
        imageUrl: 'https://img.freepik.com/premium-photo/healthy-corn-flakes-with-milk-breakfast_752567-6067.jpg',
    },
    {
        name: 'Vegetable Cutlet',
        description: 'Crispy fried patties made with mixed vegetables and spices.',
        category: 'breakfast',
        price: 149,
        rating: 4.2,
        hearts: 73,
        total: 149,
        imageUrl: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/06/veg-cutlet.jpg',
    },
    {
        name: 'Suji Halwa',
        description: 'Sweet semolina dessert cooked with ghee, sugar, and nuts.',
        category: 'breakfast',
        price: 139,
        rating: 3.9,
        hearts: 80,
        total: 139,
        imageUrl: 'https://maayeka.com/wp-content/uploads/2012/01/sooji-ka-halwa-2.jpg',
    },
    {
        name: 'Vegetable Frankie Roll',
        description: 'Soft roll filled with spiced veggies and sauces.',
        category: 'breakfast',
        price: 169,
        rating: 4.1,
        hearts: 66,
        total: 169,
        imageUrl: 'https://i0.wp.com/ahappytreat.com/wp-content/uploads/2018/01/DSC_0653.jpg?fit=6000%2C4000&ssl=1',
    },
  
    {
        name: 'Peanut Butter Sandwich',
        description: 'Bread layered with creamy peanut butter for a quick bite.',
        category: 'breakfast',
        price: 129,
        rating: 3.8,
        hearts: 52,
        total: 129,
        imageUrl: 'https://www.pcrm.org/sites/default/files/2019-09/Butter_0.jpg',
    },
    {
        name: 'Vegetable Dal Pakwan',
        description: 'Crispy pakwan served with spiced chana dal.',
        category: 'breakfast',
        price: 189,
        rating: 4.4,
        hearts: 85,
        total: 189,
        imageUrl: 'https://t4.ftcdn.net/jpg/03/17/57/19/360_F_317571924_efTPS6yfx5B16UbLGm4PfIPB0cS9liAF.jpg',
    },
    {
        name: 'Simple Khakhra Platter',
        description: 'Crispy khakhra served with chutney and pickle.',
        category: 'breakfast',
        price: 129,
        rating: 3.9,
        hearts: 80,
        total: 129,
        imageUrl: 'https://thestateplate.com/cdn/shop/products/MasalaKhakhra_c_lifetsyle_41e5d721-1def-438b-8c1e-c8126196ffc9.png?v=1680932198&width=416',
    },

    // —— Lunch ——
    {
        name: 'Dal Fry & Jeera Rice',
        description: 'Classic yellow dal tempered with spices, served with cumin rice.',
        category: 'lunch',
        price: 249,
        rating: 4.3,
        hearts: 82,
        total: 249,
        imageUrl: 'https://i.ytimg.com/vi/LF2iFAxXD1c/maxresdefault.jpg',
    },
    {
        name: 'Chole Masala & Kulcha',
        description: 'Spicy chickpea curry served with soft buttered kulcha.',
        category: 'lunch',
        price: 299,
        rating: 4.6,
        hearts: 110,
        total: 299,
        imageUrl: 'https://madhurasrecipe.com/wp-content/uploads/2020/10/Chole-Masala-Marathi-Recipe.jpg',
    },
    {
        name: 'Vegetable Biryani with Raita',
        description: 'Aromatic basmati rice cooked with vegetables and served with raita.',
        category: 'lunch',
        price: 319,
        rating: 4.5,
        hearts: 95,
        total: 319,
        imageUrl: 'https://maisonmarmite.com/wp-content/uploads/2023/12/Biryani-Legumes-Raita-Concombre-01-ok-2-1320x940.jpg',
    },
    {
        name: 'Paneer Butter Masala & Naan',
        description: 'Rich and creamy paneer curry served with soft butter naan.',
        category: 'lunch',
        price: 349,
        rating: 4.7,
        hearts: 130,
        total: 349,
        imageUrl: 'https://mealpractice.b-cdn.net/220914569881718784/paneer-tikka-masala-with-garlic-naan-and-cucumber-yogurt-salad-bvaiUkeUQ4.webp',
    },
    
    {
        name: 'Paneer Makhani & Jeera Rice',
        description: 'Creamy tomato gravy with paneer, cumin rice, and mint raita.',
        category: 'lunch',
        price: 379,
        rating: 4.8,
        hearts: 106,
        total: 379,
        imageUrl: 'https://i.redd.it/9tnea6wps4971.jpg',
    },
   
    {
        name: 'Crispy Veggie Burger & Fries',
        description: 'House veg patty, cheddar, caramelized onion, pickles, and hand-cut fries.',
        category: 'lunch',
        price: 329,
        rating: 4.4,
        hearts: 92,
        total: 329,
        imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=85',
    },
    
    {
        name: 'Rajma Masala with Jeera Rice',
        description: 'Slow-simmered kidney beans in onion-tomato masala with cumin rice.',
        category: 'lunch',
        price: 269,
        rating: 4.6,
        hearts: 102,
        total: 269,
        imageUrl: 'https://www.foodiaq.com/wp-content/uploads/2025/10/Rajma-masala-with-jeera-rice.jpg',
    },
    {
        name: 'Thai Green Curry Rice',
        description: 'Coconut vegetable curry, Thai basil, and jasmine rice.',
        category: 'lunch',
        price: 359,
        rating: 4.5,
        hearts: 87,
        total: 359,
        imageUrl: 'https://im.pluckk.in/unsafe/1200x0/uploads/14778-delhi-app-2.png',
    },

    {
        name: 'Dal Tadka & Steamed Rice',
        description: 'Yellow lentils tempered with garlic and spices, served with plain rice.',
        category: 'lunch',
        price: 249,
        rating: 3.5,
        hearts: 78,
        total: 249,
        imageUrl: 'https://simplysimplecooking.net/wp-content/uploads/2023/11/dal-tadka.webp',
    },
    {
        name: 'Veg Pulao with Raita',
        description: 'Fragrant basmati rice cooked with vegetables and mild spices.',
        category: 'lunch',
        price: 259,
        rating: 4.4,
        hearts: 94,
        total: 259,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiC9zf8GrmHHvr9rj-q-KwgOUQEB8hH70tBA&s',
    },
    {
        name: 'Chole Bhature',
        description: 'Spicy chickpea curry served with fluffy fried bhature.',
        category: 'lunch',
        price: 299,
        rating: 4.7,
        hearts: 110,
        total: 299,
        imageUrl: 'https://saptrishifoods.com/cdn/shop/articles/cholebhature.png?v=1745488999',
    },
    {
        name: 'Vegetable Biryani',
        description: 'Aromatic rice layered with spiced vegetables and herbs.',
        category: 'lunch',
        price: 319,
        rating: 4.6,
        hearts: 95,
        total: 319,
        imageUrl: 'https://www.madhuseverydayindian.com/wp-content/uploads/2022/11/easy-vegetable-biryani.jpg',
    },
    {
        name: 'Palak Paneer & Roti',
        description: 'Creamy spinach gravy with paneer served with soft rotis.',
        category: 'lunch',
        price: 349,
        rating: 4.7,
        hearts: 120,
        total: 349,
        imageUrl:'https://blog.pureindianfoods.com/wp-content/uploads/2019/05/palak-paneer.jpg',
    },
    {
        name: 'Kadhi Pakora with Rice',
        description: 'Tangy yogurt curry with gram flour fritters and steamed rice.',
        category: 'lunch',
        price: 269,
        rating: 4.5,
        hearts: 69,
        total: 269,
        imageUrl: 'https://sweetnspiceodyssey.com/images/uploads/Vegan-Kadhi-Pakora-01.jpg',
    },
    
    {
        name: 'Manchurian with Fried Rice',
        description: 'Vegetable balls in spicy sauce served with fried rice.',
        category: 'lunch',
        price: 289,
        rating: 4.5,
        hearts: 0,
        total: 289,
        imageUrl: 'https://thetableofspice.com/wp-content/uploads/2022/09/DSC_2077.jpg',
    },
    {
        name: 'Stuffed Capsicum Curry & Roti',
        description: 'Capsicum stuffed with spiced potato filling served with roti.',
        category: 'lunch',
        price: 279,
        rating: 4.4,
        hearts: 0,
        total: 279,
        imageUrl: 'https://www.pepperonpizza.com/wp-content/uploads/2015/04/Stuffed-Capsicum-Peppers_F.jpg',
    },
    {
        name: 'Mix Veg Curry & Paratha',
        description: 'Seasonal vegetables cooked in rich gravy with layered paratha.',
        category: 'lunch',
        price: 299,
        rating: 4.5,
        hearts: 0,
        total: 299,
        imageUrl: 'https://infinitybiryani.com/wp-content/uploads/2024/09/Mix-Veg-Curry-Parotha.webp',
    },
    {
        name: 'Paneer Tikka Wrap',
        description: 'Grilled paneer tikka wrapped in soft roti with sauces.',
        category: 'lunch',
        price: 249,
        rating: 3.5,
        hearts: 0,
        total: 249,
        imageUrl: 'https://kebabistaan.in/wp-content/uploads/2019/08/paneer-roll.jpg',
    },
    {
        name: 'Masala Khichdi',
        description: 'Comforting rice and lentil dish cooked with spices and veggies.',
        category: 'lunch',
        price: 219,
        rating: 4.3,
        hearts: 0,
        total: 219,
        imageUrl: 'https://www.chefajaychopra.com/assets/img/recipe/1-1666340067MasalaKhichdi1webp.webp',
    },
    {
        name: 'Vegetable Stuffed Paratha Combo',
        description: 'Assorted stuffed parathas served with curd and pickle.',
        category: 'lunch',
        price: 279,
        rating: 4.6,
        hearts: 0,
        total: 279,
        imageUrl: 'https://www.sharmispassions.com/wp-content/uploads/2020/12/8518546820_2172354d93_o-430x375.jpg',
    },
    {
        name: 'Aloo Gobi & Roti',
        description: 'Classic potato and cauliflower curry served with soft wheat rotis.',
        category: 'lunch',
        price: 249,
        rating: 4.3,
        hearts: 78,
        total: 249,
        imageUrl: 'https://thumbs.dreamstime.com/b/indian-dish-punjabi-cauliflower-potato-aloo-gobhi-matar-curry-roti-flatbread-salad-meal-109347366.jpg',
    },
    {
        name: 'Baingan Bharta & Roti',
        description: 'Smoky mashed brinjal cooked with spices, served with fresh rotis.',
        category: 'lunch',
        price: 259,
        rating: 4.2,
        hearts: 74,
        total: 259,
        imageUrl: 'https://i.ytimg.com/vi/Lc6isU5walM/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLByAP_sFo77FTHK9PrmseOYBQPVRA',
    },
    {
        name: 'Veg Kofta Curry & Rice',
        description: 'Soft vegetable dumplings in rich gravy served with steamed rice.',
        category: 'lunch',
        price: 289,
        rating: 4.5,
        hearts: 92,
        total: 289,
        imageUrl: 'https://mealpractice.b-cdn.net/219550215785549824/mixed-vegetable-kofta-in-tomato-gravy-with-jeera-rice-and-pickled-onions-c0XPDs7Mka.webp',
    },
    {
        name: 'Tawa Pulao',
        description: 'Spicy Mumbai-style rice cooked with vegetables and pav bhaji masala.',
        category: 'lunch',
        price: 229,
        rating: 3,
        hearts: 85,
        total: 229,
        imageUrl: 'https://madhurasrecipe.com/wp-content/uploads/2020/10/Tawa-Pulao-Marathi-Recipe.jpg',
    },
    {
        name: 'Gujarati Dal & Rice',
        description: 'Sweet and tangy Gujarati dal served with steamed rice.',
        category: 'lunch',
        price: 219,
        rating: 4.3,
        hearts: 80,
        total: 219,
        imageUrl: 'https://www.nehascookbook.com/wp-content/uploads/2020/11/Lasuni-dal-bhaat-WS.jpg',
    },

    // —— Dinner ——
   // 35 Indian Dinner Items (No repeat, imageUrl empty)


    {
        name: 'Baingan Bharta & Missi Roti',
        description: 'Smoky mashed eggplant with spices served with missi roti.',
        category: 'dinner',
        price: 319,
        rating: 4.6,
        hearts: 88,
        total: 319,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTf9F_FS2FnMBIVpMtPZLSRbvP9n5WaVv6igw&s',
    },
    {
        name: 'Dal Makhani & Garlic Naan',
        description: 'Creamy black lentils slow-cooked and served with garlic naan.',
        category: 'dinner',
        price: 399,
        rating: 4.8,
        hearts: 120,
        total: 399,
        imageUrl: 'https://media-cdn.tripadvisor.com/media/photo-s/1c/a5/25/36/chulha-s-dal-makhani.jpg',
    },
    {
        name: 'Malai Kofta & Butter Naan',
        description: 'Soft paneer koftas in rich gravy with butter naan.',
        category: 'dinner',
        price: 429,
        rating: 4.7,
        hearts: 110,
        total: 429,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWT25nYInsCggusUivSeCNmQB0NlHAZT2WDg&s',
    },
    {
        name: 'Paneer Tikka Platter',
        description: 'Grilled paneer tikka served with dal, roti, and salad.',
        category: 'dinner',
        price: 499,
        rating: 4.6,
        hearts: 105,
        total: 499,
        imageUrl: 'https://lemoninginger.com/wp-content/uploads/2016/01/1601_Snacks_TandooriPaneerTikka-002.jpg',
    },
    
    // New items start 👇
    
    {
        name: 'Paneer Butter Masala & Naan',
        description: 'Rich creamy paneer curry served with butter naan.',
        category: 'dinner',
        price: 389,
        rating: 4.7,
        hearts: 130,
        total: 389,
        imageUrl: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgIhLcOIgSfPph9kwyJScX0oZOf9W6XT26Chnlc5uXPP4C8_52cTsozMURL_SDruHd-DQtC9GLHqWKFvqHvnWlsqULIkpwga-6KTUiXW1btD7KQI7oNmljdwykZ1WGZB7QZr8fsqGgqoy4/s2048/paneer+butter+masala+15.JPG',
    },
    {
        name: 'Chole Masala & Roti',
        description: 'Spicy chickpea curry served with soft rotis.',
        category: 'dinner',
        price: 299,
        rating: 3,
        hearts: 95,
        total: 299,
        imageUrl: 'https://i.redd.it/rqltqtyzon771.jpg',
    },
    {
        name: 'Rajma Masala & Rice',
        description: 'Kidney beans cooked in thick gravy with steamed rice.',
        category: 'dinner',
        price: 289,
        rating: 4.5,
        hearts: 90,
        total: 289,
        imageUrl: 'https://images.squarespace-cdn.com/content/v1/5ea3b22556f3d073f3d9cae4/e37ea0ac-2f37-4df2-8e1e-3678f2f80fee/IMG_0856.jpg',
    },
    {
        name: 'Palak Paneer & Roti',
        description: 'Spinach-based paneer curry served with fresh rotis.',
        category: 'dinner',
        price: 349,
        rating: 4.6,
        hearts: 102,
        total: 349,
        imageUrl: 'https://blog.pureindianfoods.com/wp-content/uploads/2019/05/palak-paneer.jpg',
    },
    {
        name: 'Kadai Paneer & Naan',
        description: 'Paneer cooked with capsicum in spicy kadai masala.',
        category: 'dinner',
        price: 369,
        rating: 4.6,
        hearts: 98,
        total: 369,
        imageUrl: 'https://orders.popskitchen.in/storage/2024/09/image-185.png',
    },
    {
        name: 'Mix Veg Curry & Roti',
        description: 'Seasonal vegetables cooked in rich gravy.',
        category: 'dinner',
        price: 279,
        rating: 4.3,
        hearts: 75,
        total: 279,
        imageUrl: 'https://www.cookingandme.com/wp-content/uploads/2012/12/8234784286_ee408b27e6_z.jpg',
    },
    {
        name: 'Aloo Gobi & Roti',
        description: 'Potato and cauliflower curry served with roti.',
        category: 'dinner',
        price: 249,
        rating: 4.3,
        hearts: 70,
        total: 249,
        imageUrl: 'https://thumbs.dreamstime.com/b/indian-dish-punjabi-cauliflower-potato-aloo-gobhi-matar-curry-roti-flatbread-salad-meal-109347366.jpg',
    },
    {
        name: 'Jeera Rice & Dal Tadka',
        description: 'Cumin rice served with flavorful dal tadka.',
        category: 'dinner',
        price: 269,
        rating: 4.4,
        hearts: 82,
        total: 269,
        imageUrl: 'https://i.ytimg.com/vi/LF2iFAxXD1c/maxresdefault.jpg',
    },
    {
        name: 'Veg Biryani & Raita',
        description: 'Spiced rice with vegetables served with raita.',
        category: 'dinner',
        price: 319,
        rating: 4.6,
        hearts: 100,
        total: 319,
        imageUrl: 'https://www.madhuseverydayindian.com/wp-content/uploads/2022/11/easy-vegetable-biryani.jpg',
    },
    {
        name: 'Kadhi Pakora & Rice',
        description: 'Yogurt-based curry with pakoras and steamed rice.',
        category: 'dinner',
        price: 279,
        rating: 4.4,
        hearts: 85,
        total: 279,
        imageUrl: 'https://sweetnspiceodyssey.com/images/uploads/Vegan-Kadhi-Pakora-01.jpg',
    },
    {
        name: 'Stuffed Paratha Combo',
        description: 'Assorted stuffed parathas with curd and pickle.',
        category: 'dinner',
        price: 299,
        rating: 4.5,
        hearts: 90,
        total: 299,
        imageUrl: 'https://c.ndtvimg.com/2023-04/oo2r2eb8_aloo-paratha_625x300_28_April_23.jpg?im=FaceCrop,algorithm=dnn,width=1200,height=886',
    },
    {
        name: 'Vegetable Kofta Curry & Naan',
        description: 'Soft veg koftas in rich gravy with naan.',
        category: 'dinner',
        price: 349,
        rating: 4.5,
        hearts: 88,
        total: 349,
        imageUrl: 'https://i.ytimg.com/vi/zPUx2ThXGHI/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCU6mKCJ2IVAhi2Pf8pbd_8aVsBPg',
    },
    {
        name: 'Tandoori Roti & Dal Fry',
        description: 'Simple dal fry served with tandoori roti.',
        category: 'dinner',
        price: 259,
        rating: 4.2,
        hearts: 65,
        total: 259,
        imageUrl: 'https://media.istockphoto.com/id/1326660354/photo/indian-popular-food-dal-fry-or-traditional-dal-tadka-curry.jpg?s=612x612&w=0&k=20&c=hpmRhBIuzcpZsGqagSGivlmDVjv0bC-n_lGHTk12AyI=',
    },
    {
        name: 'Paneer Bhurji & Pav',
        description: 'Spicy scrambled paneer served with butter pav.',
        category: 'dinner',
        price: 289,
        rating: 4.4,
        hearts: 80,
        total: 289,
        imageUrl: 'https://img.freepik.com/premium-photo/paneer-bhurji-with-pav-is-spicy-paneer-curry-dish-made-up-paneer-onion-tomatoes-indian-spices-served-with-buns-pav-isolated-rustic-wooden-background-selective-focus_726363-966.jpg',
    },
    {
        name: 'Vegetable Pulao',
        description: 'Mildly spiced rice with vegetables.',
        category: 'dinner',
        price: 249,
        rating: 4.2,
        hearts: 72,
        total: 249,
        imageUrl: 'https://www.funfoodfrolic.com/wp-content/uploads/2022/05/Veg-Pulao-Blog.jpg',
    },
    {
        name: 'Masala Khichdi',
        description: 'Comfort rice and dal dish with spices.',
        category: 'dinner',
        price: 229,
        rating: 4.1,
        hearts: 60,
        total: 229,
        imageUrl: 'https://www.chefajaychopra.com/assets/img/recipe/1-1666340067MasalaKhichdi1webp.webp',
    },
    {
        name: 'Bhindi Masala & Roti',
        description: 'Okra cooked with spices served with roti.',
        category: 'dinner',
        price: 259,
        rating: 4.3,
        hearts: 68,
        total: 259,
        imageUrl: 'https://www.bigbasket.com/media/uploads/recipe/w-l/574_1.jpg',
    },
    {
        name: 'Sev Tameta & Roti',
        description: 'Gujarati curry made with tomatoes and sev.',
        category: 'dinner',
        price: 239,
        rating: 4.4,
        hearts: 77,
        total: 239,
        imageUrl: 'https://fromzerotocurry.com/wp-content/uploads/2022/03/IMGP6026-4.jpg',
    },
    {
        name: 'Undhiyu & Puri',
        description: 'Traditional Gujarati mixed vegetable dish with puri.',
        category: 'dinner',
        price: 349,
        rating: 4.6,
        hearts: 95,
        total: 349,
        imageUrl: 'https://images.slurrp.com/prodrecipe_images/cms/p3d00gu3tp.webp',
    },
    {
        name: 'Thepla & Curd Combo',
        description: 'Soft methi thepla served with fresh curd.',
        category: 'dinner',
        price: 219,
        rating: 3.5,
        hearts: 63,
        total: 219,
        imageUrl: 'https://ministryofcurry.com/wp-content/uploads/2022/04/methi-thepla.jpg',
    },
    {
        name: 'Dal Dhokli',
        description: 'Gujarati comfort dish with wheat dumplings in dal.',
        category: 'dinner',
        price: 249,
        rating: 4.5,
        hearts: 85,
        total: 249,
        imageUrl: 'https://www.cookingcarnival.com/wp-content/uploads/2021/07/Dal-Dhokli-7.jpg',
    },
    {
        name: 'Handvo Platter',
        description: 'Savory baked lentil cake served with chutney.',
        category: 'dinner',
        price: 229,
        rating: 4.3,
        hearts: 70,
        total: 229,
        imageUrl: 'https://pipingpotcurry.com/wp-content/uploads/2021/02/Baked-handvo-recipe-1-1024x1024.jpg',
    },
    {
        name: 'Vegetable Handi & Naan',
        description: 'Mixed vegetables cooked in handi style gravy.',
        category: 'dinner',
        price: 359,
        rating: 2.5,
        hearts: 92,
        total: 359,
        imageUrl: 'https://elephantatta.com/wp-content/uploads/2018/05/veg-handi-reciepe-main-page.jpg.webp',
    },
    {
        name: 'Paneer Lababdar & Roti',
        description: 'Rich paneer curry with creamy tomato gravy.',
        category: 'dinner',
        price: 379,
        rating: 4.6,
        hearts: 97,
        total: 379,
        imageUrl: 'https://myfoodstory.com/wp-content/uploads/2022/01/Paneer-Lababdar-3.jpg',
    },
    {
        name: 'Dal Palak & Rice',
        description: 'Lentils cooked with spinach served with rice.',
        category: 'dinner',
        price: 269,
        rating: 4.3,
        hearts: 74,
        total: 269,
        imageUrl: 'https://www.twospoons.ca/wp-content/uploads/2022/01/dal-palak-recipe-vegan-gluten-free-twospoons-8.jpg',
    },
    {
        name: 'Tawa Roti & Mix Dal',
        description: 'Simple roti served with mixed lentil curry.',
        category: 'dinner',
        price: 239,
        rating: 3.8,
        hearts: 66,
        total: 239,
        imageUrl: 'https://www.foodandwine.com/thmb/3Inj7GRvnz35RLkSfUIrKIrW3UE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/tadka-dal-with-roti-FT-RECIPE0121-8543a4864b454dfab2f8cdc5b72c7c5f.jpg',
    },
    // —— Mexican ——
    {
        name: 'Veg Mexican Rice Bowl',
        description: 'Spiced rice with beans, corn, veggies, and mild salsa.',
        category: 'mexican',
        price: 289,
        rating: 4.3,
        hearts: 72,
        total: 289,
        imageUrl: 'https://kalynskitchen.com/wp-content/uploads/2013/06/1-650-brown-rice-mexican-bowl-500-kalynskitchen.jpg',
    },
    {
        name: 'Bean & Cheese Burrito',
        description: 'Soft tortilla filled with refried beans, cheese, and mild spices.',
        category: 'mexican',
        price: 279,
        rating: 3,
        hearts: 68,
        total: 279,
        imageUrl: 'https://whatsgabycooking.com/wp-content/uploads/2024/08/WGC-Bean-and-Cheese-Burritos-2.jpg',
    },
    {
        name: 'Veg Fajita Wrap',
        description: 'Grilled veggies wrapped in tortilla with tangy sauce.',
        category: 'mexican',
        price: 299,
        rating: 4,
        hearts: 80,
        total: 299,
        imageUrl: 'https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/vegetable_fajitas_92165_16x9.jpg',
    },
    {
        name: 'Mexican Corn Salad',
        description: 'Sweet corn mixed with spices, lime, and creamy dressing.',
        category: 'mexican',
        price: 199,
        rating: 4.1,
        hearts: 60,
        total: 199,
        imageUrl: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/mexican-corn-salad-738cedc.jpg',
    },
    {
        name: 'Guacamole & Chips',
        description: 'Fresh avocado dip served with crispy tortilla chips.',
        category: 'mexican',
        price: 249,
        rating: 4.0,
        hearts: 90,
        total: 249,
        imageUrl: 'https://www.becel.ca/-/media/Project/Upfield/Brands/Becel-CA/Becel-Canada/Assets/Recipes/Synced-images/2fbfa380-06e2-4659-9199-adb978f642ce.jpg?rev=b33682271b3c40a28e0caaa4f9a93b07',
    },
    {
        name: 'Veg Chimichanga',
        description: 'Deep-fried burrito stuffed with beans and veggies.',
        category: 'mexican',
        price: 319,
        rating: 4.3,
        hearts: 75,
        total: 319,
        imageUrl: 'https://i.ytimg.com/vi/LupsjFPxc8o/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLA-8_xWcGSVk8d1S4-IZreXWIKOSQ',
    },
    {
        name: 'Cheesy Jalapeno Poppers',
        description: 'Jalapenos stuffed with cheese and lightly fried.',
        category: 'mexican',
        price: 269,
        rating: 4.2,
        hearts: 65,
        total: 269,
        imageUrl: 'https://d1uz88p17r663j.cloudfront.net/original/834207a91d8356a0f663f7f78359f97e_Mac-n-Cheese-Jalapeno-Poppers-24.jpg',
    },
    {
        name: 'Mexican Street Corn (Elote)',
        description: 'Grilled corn with cheese, chili powder, and lime.',
        category: 'mexican',
        price: 179,
        rating: 4.4,
        hearts: 78,
        total: 179,
        imageUrl: 'https://www.seriouseats.com/thmb/6tXTfp2-QGmVLazenk672sgUdRw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20210630-elotes-melissa-hom-seriouseats-5-895932860b0d4f88b1b330e574036305.jpg',
    },
    {
        name: 'Veg Taco Salad Bowl',
        description: 'Crispy taco shell filled with beans, lettuce, and salsa.',
        category: 'mexican',
        price: 289,
        rating: 4.0,
        hearts: 70,
        total: 289,
        imageUrl: 'https://www.thelastfoodblog.com/wp-content/uploads/2018/02/vegetarian-taco-salad-f_i-3.jpg',
    },
    {
        name: 'Refried Beans & Rice Plate',
        description: 'Classic beans served with Mexican-style rice.',
        category: 'mexican',
        price: 259,
        rating: 4.1,
        hearts: 58,
        total: 259,
        imageUrl: 'https://www.foodnetwork.com/content/dam/images/food/fullset/2020/10/28/0/MW606_refried-beans-and-rice-bowl_s4x3.jpg',
    },
    {
        name: 'Cheese Stuffed Queso Balls',
        description: 'Crispy balls filled with melted cheese and spices.',
        category: 'mexican',
        price: 249,
        rating: 4.2,
        hearts: 62,
        total: 249,
        imageUrl: 'https://www.mycolombianrecipes.com/wp-content/uploads/2013/12/Bolitas-de-Yuca-con-Queso.jpg',
    },
    {
        name: 'Veg Enchilada Rice Combo',
        description: 'Enchilada served with rice and beans on the side.',
        category: 'mexican',
        price: 329,
        rating: 4.4,
        hearts: 82,
        total: 329,
        imageUrl: 'https://www.mexicanplease.com/wp-content/uploads/2022/05/black-bean-and-rice-enchiladas-13.jpg',
    },
    {
        name: 'Mexican Veg Loaded Fries',
        description: 'Fries topped with beans, cheese, jalapenos, and sauces.',
        category: 'mexican',
        price: 239,
        rating: 4.0,
        hearts: 76,
        total: 239,
        imageUrl: 'https://img.taste.com.au/D28D_mq3/w1200-h1200-cfill-q80/taste/2018/05/loaded-vegan-fries-137370-1.jpg',
    },

    // —— Italian ——
    {
        name: 'Truffle Mushroom Tagliatelle',
        description: 'Hand-cut pasta, mixed mushrooms, truffle oil, and pecorino.',
        category: 'italian',
        price: 449,
        rating: 4.7,
        hearts: 0,
        total: 449,
        imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=85',
    },
    {
        name: 'Wood-Fired Margherita Pizza',
        description: 'San Marzano tomatoes, mozzarella di bufala, basil, olive oil.',
        category: 'italian',
        price: 399,
        rating: 4.6,
        hearts: 0,
        total: 399,
        imageUrl: 'https://au.ooni.com/cdn/shop/articles/20220211142645-margherita-9920.jpg?v=1737368217',
    },
    {
        name: 'Roasted Vegetable Lasagna',
        description: 'Layers of pasta, grilled zucchini & peppers, ricotta, béchamel, tomato.',
        category: 'italian',
        price: 399,
        rating: 4.6,
        hearts: 0,
        total: 399,
        imageUrl: 'https://cdn.allotta.io/image/upload/v1718730186/dxp-images/brands/Recipes/global-recipes-heinz-nz/roasted-vegetable-lasagne/generated/roasted-vegetable-lasagne-218087.jpg'
    },
    {
        name: 'Lemon Aglio Olio Linguine',
        description: 'Linguine with olive oil, garlic, chili flakes, parsley, and cherry tomatoes.',
        category: 'italian',
        price: 329,
        rating: 4.5,
        hearts: 0,
        total: 329,
        imageUrl: 'https://images.unsplash.com/photo-1611270629569-8b357cb88da9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=85',
    },
    {
        name: 'Bruschetta Assortito',
        description: 'Toasted ciabatta — tomato basil, olive tapenade, whipped ricotta.',
        category: 'italian',
        price: 249,
        rating: 4.3,
        hearts: 0,
        total: 249,
        imageUrl: 'https://grantourismotravels.com/wp-content/uploads/2019/03/Authentic-Tomato-Basil-Bruschetta-Recipe-Copyright-2022-Terence-Carter-Grantourismo-T.jpg',
    },

    // —— Desserts ——
    {
        name: 'Belgian Chocolate Lava Cake',
        description: 'Warm flowing center, vanilla gelato, berry compote.',
        category: 'desserts',
        price: 229,
        rating: 4.8,
        hearts: 0,
        total: 229,
        imageUrl: 'https://preppykitchen.com/wp-content/uploads/2022/03/Chocolate-Lava-Cake-Recipe.jpg',
    },
    {
        name: 'New York Cheesecake Slice',
        description: 'Baked cheesecake, berry coulis, lightly whipped cream.',
        category: 'desserts',
        price: 199,
        rating: 4.5,
        hearts: 0,
        total: 199,
        imageUrl: 'https://www.seriouseats.com/thmb/deFCx8YVoK5b_rXrIco5oc2Qo4I=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__2019__05__20190520-cheesecake-vicky-wasik-34-16488b3671ae47b5b29eb7124dbaf938.jpg',
    },
    {
        name: 'Mango Kulfi Stick Trio',
        description: 'Saffron-kesar kulfi, pistachio crumble, rose drizzle.',
        category: 'desserts',
        price: 179,
        rating: 4.6,
        hearts: 0,
        total: 179,
        imageUrl: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=85',
    },
    {
        name: 'Tiramisu Signature',
        description: 'Mascarpone, espresso-soaked sponge, cocoa — classic slice.',
        category: 'desserts',
        price: 219,
        rating: 4.7,
        hearts: 0,
        total: 219,
        imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=85',
    },
    {
        name: 'Artisan Gelato Duo',
        description: 'Two scoops: pistachio, stracciatella, or salted caramel.',
        category: 'desserts',
        price: 189,
        rating: 4.4,
        hearts: 0,
        total: 189,
        imageUrl: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=85',
    },

    // —— Drinks ——
    
    // —— More breakfast ——
    {
        name: 'Indori Poha Jalebi Combo',
        description: 'Fluffy poha with sev, lemon, coriander, and mini jalebi on the side.',
        category: 'breakfast',
        price: 149,
        rating: 4.5,
        hearts: 0,
        total: 149,
        imageUrl: 'https://www.cuisineindiasociety.in/wp/wp-content/uploads/2025/05/Untitled-1.jpg',
    },
    {
        name: 'Vegetable Upma & Coconut Chutney',
        description: 'Semolina upma with carrots, beans, curry leaves, and fresh chutney.',
        category: 'breakfast',
        price: 139,
        rating: 4.4,
        hearts: 0,
        total: 139,
        imageUrl: 'https://thumbs.dreamstime.com/b/delicious-plate-vegetable-upma-served-coconut-chutney-traditional-south-indian-breakfast-plate-vegetable-upma-366200696.jpg',
    },
    {
        name: 'Curd Rice & Pickle Bowl',
        description: 'Chilled tempered yogurt rice with cucumber, mustard, and mango pickle.',
        category: 'breakfast',
        price: 129,
        rating: 4.3,
        hearts: 0,
        total: 129,
        imageUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=85',
    },

    // —— More lunch ——
    {
        name: 'Veg Kolhapuri Thali',
        description: 'Spicy mixed veg gravy, chapati, salad, pickle, and steamed rice.',
        category: 'lunch',
        price: 289,
        rating: 4.5,
        hearts: 120,
        total: 289,
        imageUrl: 'https://media-cdn.tripadvisor.com/media/photo-s/1a/d9/7d/b5/kolhapuri-non-veg-thali.jpg',
    },
    {
        name: 'Roasted Corn & Bean Salad Bowl',
        description: 'Charred corn, black beans, lime, cilantro, and quinoa base.',
        category: 'lunch',
        price: 259,
        rating: 4.3,
        hearts: 78,
        total: 259,
        imageUrl: 'https://www.onionringsandthings.com/wp-content/uploads/2015/08/roasted-corn-black-bean-salad-1.jpg',
    },
    {
        name: 'Tomato Basil Soup & Focaccia',
        description: 'Slow-roasted tomato soup with olive oil drizzle and warm herb focaccia.',
        category: 'lunch',
        price: 219,
        rating: 4.4,
        hearts: 85,
        total: 219,
        imageUrl: 'https://cdn.loveandlemons.com/wp-content/uploads/2020/09/tomato-basil-soup-recipe.jpg',
    },

    // —— More dinner ——
    {
        name: 'Palak Paneer & Tandoori Roti',
        description: 'Creamy spinach with paneer cubes, garlic tempering, and hot roti.',
        category: 'dinner',
        price: 379,
        rating: 4.7,
        hearts: 0,
        total: 379,
        imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=85',
    },
    {
        name: 'Handi Veg Biryani',
        description: 'Fragrant basmati with layered vegetables, fried onions, and raita.',
        category: 'dinner',
        price: 349,
        rating: 4.6,
        hearts: 0,
        total: 349,
        imageUrl: 'https://kannanskitchen.com/wp-content/uploads/2021/04/DSC_1079_1.jpg',
    },
    

    // —— More mexican ——
    {
        name: 'Street Corn Elote Cup',
        description: 'Grilled corn kernels, lime mayo, cotija-style cheese, and chili dust.',
        category: 'mexican',
        price: 179,
        rating: 4.4,
        hearts: 0,
        total: 179,
        imageUrl: 'https://www.caciquefoods.com/wp-content/uploads/2022/06/CACIQUE-ELOTE-CUPS.jpg',
    },
    {
        name: 'Guacamole & Blue Corn Chips',
        description: 'Chunky avocado dip with lime, tomato, onion, and warm chips.',
        category: 'mexican',
        price: 199,
        rating: 4.3,
        hearts: 0,
        total: 199,
        imageUrl: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=85',
    },
    {
        name: 'Sizzling Veg Fajitas',
        description: 'Sizzler plate of peppers, onions, mushrooms, tortillas, and salsa trio.',
        category: 'mexican',
        price: 339,
        rating: 4.5,
        hearts: 0,
        total: 339,
        imageUrl: 'https://www.connoisseurusveg.com/wp-content/uploads/2021/07/vegetable-fajitas-square.jpg',
    },

    
  
    // —— More desserts ——
    {
        name: 'Belgian Chocolate Lava Cake',
        description: 'Warm flowing center, vanilla gelato, berry compote.',
        category: 'desserts',
        price: 229,
        rating: 4.8,
        hearts: 120,
        total: 229,
        imageUrl: 'https://preppykitchen.com/wp-content/uploads/2022/03/Chocolate-Lava-Cake-Recipe.jpg',
    },
    {
        name: 'New York Cheesecake Slice',
        description: 'Baked cheesecake, berry coulis, lightly whipped cream.',
        category: 'desserts',
        price: 199,
        rating: 3.5,
        hearts: 95,
        total: 199,
        imageUrl: 'https://img.taste.com.au/O8JC4F3Q/taste/2016/11/new-york-cheesecake-40742-1.jpeg',
    },
    {
        name: 'Mango Kulfi Stick Trio',
        description: 'Saffron-kesar kulfi, pistachio crumble, rose drizzle.',
        category: 'desserts',
        price: 179,
        rating: 4.6,
        hearts: 88,
        total: 179,
        imageUrl: 'https://5.imimg.com/data5/SELLER/Default/2023/3/294179502/RC/BZ/YM/109172480/mango-kulfi-500x500.jpeg',
    },
    {
        name: 'Tiramisu Signature',
        description: 'Mascarpone, espresso-soaked sponge, cocoa — classic slice.',
        category: 'desserts',
        price: 219,
        rating: 4.7,
        hearts: 105,
        total: 219,
        imageUrl: 'https://popmenucloud.com/cdn-cgi/image/width%3D1200%2Cheight%3D1200%2Cfit%3Dscale-down%2Cformat%3Dauto%2Cquality%3D60/xblyfktw/10559d4b-5ab3-4232-948a-b4213a043e8a.jpg',
    },
    {
        name: 'Artisan Gelato Duo',
        description: 'Two scoops: pistachio, stracciatella, or salted caramel.',
        category: 'desserts',
        price: 189,
        rating: 4.0,
        hearts: 80,
        total: 189,
        imageUrl: 'https://b.zmtcdn.com/data/pictures/9/20448599/2157a71e489149035dd31dda3023758c.jpg?fit=around|960:500&crop=960:500;*,*',
    },
    {
        name: 'Warm Gulab Jamun Rabri',
        description: 'Soft khoya dumplings in rose syrup with chilled rabri.',
        category: 'desserts',
        price: 149,
        rating: 4.7,
        hearts: 110,
        total: 149,
        imageUrl: 'https://gayathriscookspot.com/wp-content/uploads/2022/05/Gulab-Jamun-Rabdi-Box-Cake-8.jpg',
    },
    {
        name: 'Walnut Fudge Brownie',
        description: 'Dense chocolate brownie, toasted walnuts, vanilla scoop.',
        category: 'desserts',
        price: 189,
        rating: 3.7,
        hearts: 92,
        total: 189,
        imageUrl: 'https://walnuts.org/wp-content/uploads/2017/09/c360eaf60239976-87670915-D8A4-40D5-86284C189E6F9A17.jpg',
    },
    {
        name: 'Royal Falooda Glass',
        description: 'Rose milk, basil seeds, falooda sev, ice cream, and nuts.',
        category: 'desserts',
        price: 199,
        rating: 4.4,
        hearts: 85,
        total: 199,
        imageUrl: 'https://aartimadan.com/wp-content/uploads/2019/05/fALOODA-RECIPE-1.jpg',
    },
    
    // New 7 items 👇
    
    {
        name: 'Chocolate Ice Cream Sundae',
        description: 'Chocolate ice cream topped with syrup, nuts, and whipped cream.',
        category: 'desserts',
        price: 179,
        rating: 4.5,
        hearts: 90,
        total: 179,
        imageUrl: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2021/12/15/0/FNM_010122-Dark-Chocolate-Brownie-Sundae_s4x3.jpg.rend.hgtvcom.1280.1280.suffix/1639586951781.webp',
    },
    {
        name: 'Rasmalai Delight',
        description: 'Soft paneer discs soaked in sweet saffron milk.',
        category: 'desserts',
        price: 159,
        rating: 3.2,
        hearts: 68,
        total: 159,
        imageUrl: 'https://www.fnp.com/images/pr/l/v20250312160447/golden-delight-rasmalai-cake_1.jpg',
    },
    {
        name: 'Strawberry Ice Cream',
        description: 'Creamy strawberry ice cream made with real fruit pulp.',
        category: 'desserts',
        price: 149,
        rating: 3.3,
        hearts: 70,
        total: 149,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuBs2fG5B_4_hedM4oV-JRXj12WClU1bLH7w&s',
    },
    {
        name: 'Chocolate Donut',
        description: 'Soft donut coated with rich chocolate glaze.',
        category: 'desserts',
        price: 129,
        rating: 4.2,
        hearts: 65,
        total: 129,
        imageUrl: 'https://thefirstyearblog.com/wp-content/uploads/2020/10/chocolate-donuts-Square2.png',
    },
    {
        name: 'Kesar Pista Ice Cream',
        description: 'Saffron flavored ice cream with crunchy pistachios.',
        category: 'desserts',
        price: 169,
        rating: 4.4,
        hearts: 78,
        total: 169,
        imageUrl: 'https://www.mygingergarlickitchen.com/wp-content/rich-markup-images/1x1/1x1-kesar-pista-ice-cream.jpg',
    },
    {
        name: 'Caramel Custard',
        description: 'Silky smooth custard topped with caramel sauce.',
        category: 'desserts',
        price: 159,
        rating: 4.3,
        hearts: 72,
        total: 159,
        imageUrl: 'https://kitchenmai.com/wp-content/uploads/2020/08/caramel_custard_blog-e1596304249328.jpg',
    },
    {
        name: 'Choco Chip Muffin',
        description: 'Soft baked muffin loaded with chocolate chips.',
        category: 'desserts',
        price: 139,
        rating: 4.4,
        hearts: 75,
        total: 139,
        imageUrl: 'https://www.biggerbolderbaking.com/wp-content/uploads/2020/04/Classic-Chocolate-Chip-Muffins-WS-Thumbnail.jpg',
    },


    // Drinks  items
    

    
        {
            name: 'Cold Brew Tonic',
            description: 'Slow-steeped coffee, tonic water, orange peel, ice.',
            category: 'drinks',
            price: 149,
            rating: 4.4,
            hearts: 78,
            total: 149,
            imageUrl: 'https://cupcave.net/wp-content/uploads/2024/03/cold-brew-tonic-1-mar-2024.webp',
        },
        {
            name: 'Velvet Cappuccino',
            description: 'Double espresso, velvety foam, light cocoa dust.',
            category: 'drinks',
            price: 139,
            rating: 4.5,
            hearts: 85,
            total: 139,
            imageUrl: 'https://coffeeaffection.com/wp-content/uploads/2021/08/red-velvet-latte-close-up_CWIS_Shutterstock.jpg',
        },
        {
            name: 'Virgin Mojito Fizz',
            description: 'Mint, lime, soda, touch of elderflower.',
            category: 'drinks',
            price: 129,
            rating: 4.3,
            hearts: 72,
            total: 129,
            imageUrl: 'https://www.informations-pratiques.com/wp-content/uploads/2025/08/virgin-mojito.jpg',
        },
        {
            name: 'Alphonso Mango Lassi',
            description: 'Thick yogurt, ripe mango, cardamom.',
            category: 'drinks',
            price: 159,
            rating: 4.7,
            hearts: 110,
            total: 159,
            imageUrl: 'https://img.freepik.com/premium-photo/mango-lassi-yogurt-indian-popular-summer-drink-served-glass-with-whole-alphonso-aam-fruit-selective-focus_466689-25065.jpg',
        },
        {
            name: 'Masala Chai Latte',
            description: 'Spiced tea concentrate with steamed milk.',
            category: 'drinks',
            price: 119,
            rating: 4.6,
            hearts: 95,
            total: 119,
            imageUrl: 'https://img.freepik.com/premium-photo/traditional-indian-masala-chai-latte_1012122-6590.jpg',
        },
        {
            name: 'Tropical Mango Cooler',
            description: 'Mango puree, lime, and sparkling water — chilled tropical sip.',
            category: 'drinks',
            price: 109,
            rating: 4.4,
            hearts: 80,
            total: 109,
            imageUrl: 'https://img.freepik.com/premium-photo/tropical-mango-coconut-cooler-mason-jar_636537-494169.jpg',
        },
        {
            name: 'Masala Chaas Glass',
            description: 'Chaas (buttermilk) with roasted cumin, mint, and ginger.',
            category: 'drinks',
            price: 79,
            rating: 4.3,
            hearts: 70,
            total: 79,
            imageUrl: 'https://www.cookwithkushi.com/wp-content/uploads/2016/06/masala_chaas_spiced_buttermmilk.jpg',
        },
        
        // New 10 items 👇
        
        {
            name: 'Cold Coffee Classic',
            description: 'Chilled coffee blended with milk and ice cream.',
            category: 'drinks',
            price: 149,
            rating: 4.5,
            hearts: 98,
            total: 149,
            imageUrl: 'https://wallpaperaccess.com/full/3455785.jpg',
        },
        {
            name: 'Chocolate Milkshake',
            description: 'Rich chocolate shake topped with whipped cream.',
            category: 'drinks',
            price: 159,
            rating: 4.6,
            hearts: 105,
            total: 159,
            imageUrl: 'https://static.toiimg.com/photo/84170265.cms',
        },
        {
            name: 'Strawberry Milkshake',
            description: 'Fresh strawberry shake with creamy texture.',
            category: 'drinks',
            price: 149,
            rating: 4.4,
            hearts: 88,
            total: 149,
            imageUrl: 'https://www.thestatesman.com/wp-content/uploads/2019/03/strawberry-shake.jpg',
        },
        {
            name: 'Oreo Shake',
            description: 'Crushed Oreo cookies blended with milk and ice cream.',
            category: 'drinks',
            price: 169,
            rating: 4.7,
            hearts: 115,
            total: 169,
            imageUrl: 'https://insanelygoodrecipes.com/wp-content/uploads/2024/02/Oreo-Shakes-on-a-table-800x530.jpg',
        },
        {
            name: 'Fresh Lime Soda',
            description: 'Refreshing lime soda with a hint of salt and sugar.',
            category: 'drinks',
            price: 99,
            rating: 4.3,
            hearts: 75,
            total: 99,
            imageUrl: 'https://www.spiritofindiapattaya.com/wp-content/uploads/2018/08/Fresh-Lime-Soda-600x401.jpg',
        },
        {
            name: 'Watermelon Juice',
            description: 'Freshly blended watermelon juice served chilled.',
            category: 'drinks',
            price: 119,
            rating: 4.4,
            hearts: 82,
            total: 119,
            imageUrl: 'https://www.tasteofhome.com/wp-content/uploads/2019/04/watermelon-juice-shutterstock_285112223.jpg',
        },
        {
            name: 'Pineapple Juice',
            description: 'Sweet and tangy pineapple juice, freshly prepared.',
            category: 'drinks',
            price: 119,
            rating: 4.3,
            hearts: 78,
            total: 119,
            imageUrl: 'https://dwellbymichelle.com/wp-content/uploads/2022/06/DWELL-Refreshing-PIneapple-Juice-Recipe-scaled.jpg',
        },
        {
            name: 'Iced Latte',
            description: 'Chilled espresso mixed with milk and ice.',
            category: 'drinks',
            price: 139,
            rating: 4.5,
            hearts: 90,
            total: 139,
            imageUrl: 'https://i.pinimg.com/originals/bd/de/a0/bddea0e4dbe2f7a9cffa8cab5194cb74.jpg',
        },
        {
            name: 'KitKat Shake',
            description: 'Chocolate shake blended with crunchy KitKat pieces.',
            category: 'drinks',
            price: 179,
            rating: 4.6,
            hearts: 108,
            total: 179,
            imageUrl: 'https://www.bitensip.com/wp-content/uploads/2022/11/kit-kat-shake.jpg',
        },
        {
            name: 'Badam Milk',
            description: 'Warm or chilled almond milk flavored with saffron.',
            category: 'drinks',
            price: 139,
            rating: 4.5,
            hearts: 92,
            total: 139,
            imageUrl: 'https://www.thespruceeats.com/thmb/aXBZePco3iakbaZyPC4LamgwVEI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/SES-badam-milk-with-cardamom-1957418-f94ebb8b20b9421ba4688cd7570d36e0.jpg',
        },
        {
            name: 'Blue Lagoon Mocktail',
            description: 'Refreshing citrus drink with blue curacao flavor and soda.',
            category: 'drinks',
            price: 149,
            rating: 4.4,
            hearts: 86,
            total: 149,
            imageUrl: 'https://butdelicious.com/wp-content/uploads/2025/05/0-2-640-N-105.jpg',
        },
        {
            name: 'Rose Milk',
            description: 'Chilled milk flavored with rose syrup and a hint of cardamom.',
            category: 'drinks',
            price: 119,
            rating: 4.3,
            hearts: 74,
            total: 119,
            imageUrl: 'https://www.spiceupthecurry.com/wp-content/uploads/2023/04/rose-milk-recipe-3-720x720.jpg',
        },


    // —— Extra vegetarian items (more data per category) ——
    {
        name: 'Spicy Lemon Poha with Sev',
        description: 'Poha tossed with lemon, mustard seeds, curry leaves, sev, and coriander.',
        category: 'breakfast',
        price: 159,
        rating: 4.4,
        hearts: 0,
        total: 159,
        imageUrl: 'https://img.freepik.com/premium-photo/kande-pohay-aloo-poha-is-popular-indian-breakfast-recipe-made-using-flattened-rice-usually-served-with-hot-tea-served-bowl-selective-focus_466689-46977.jpg',
    },
    {
        name: 'Veg Manchurian Soup Bowl',
        description: 'Aromatic vegetable manchurian style soup with crunchy greens.',
        category: 'breakfast',
        price: 239,
        rating: 4.5,
        hearts: 0,
        total: 239,
        imageUrl: 'https://sinfullyspicy.com/wp-content/uploads/2023/12/1200-by-1200-images-1-300x300.jpg',
    },
    {
        name: 'Paneer Tikka Roll',
        description: 'Charred paneer tikka, crunchy veggies, and mint-coriander roll.',
        category: 'lunch',
        price: 329,
        rating: 4.6,
        hearts: 0,
        total: 329,
        imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=85',
    },
    {
        name: 'Veg Hakka Noodles Box',
        description: 'Wok-tossed hakka noodles with peppers, carrots, and soy-garlic glaze.',
        category: 'lunch',
        price: 309,
        rating: 4.4,
        hearts: 0,
        total: 309,
        imageUrl: 'https://thewhiskaddict.com/wp-content/uploads/2020/02/IMG_2848-2-scaled.jpg',
    },
    {
        name: 'Stuffed Mushroom & Spinach Bake',
        description: 'Oven-baked mushrooms with spinach, herbs, and cheese topping.',
        category: 'dinner',
        price: 399,
        rating: 4.6,
        hearts: 0,
        total: 399,
        imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=85',
    },
    {
        name: 'Veg Kathi Roll with Gravy',
        description: 'Kathi-style roll filled with spiced veg and served with a tangy gravy.',
        category: 'dinner',
        price: 359,
        rating: 4.5,
        hearts: 0,
        total: 359,
        imageUrl: 'https://c.ndtvimg.com/2024-02/bbvgfbmg_kathi-rolls_625x300_12_February_24.jpg',
    },
    {
        name: 'Chilli Cheese Veg Tacos',
        description: 'Soft tacos filled with chili cheese veg and pico de gallo.',
        category: 'mexican',
        price: 279,
        rating: 4.3,
        hearts: 0,
        total: 279,
        imageUrl: 'https://orientasian.in/wp-content/uploads/2020/10/0001-12188106954_20201023_114842_0000-min-1200x900.png',
    },
    {
        name: 'Mushroom Queso Dip & Nachos',
        description: 'Creamy queso dip with mushrooms served with crispy tortilla chips.',
        category: 'mexican',
        price: 249,
        rating: 4.4,
        hearts: 0,
        total: 249,
        imageUrl: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=85',
        
    },

    // Italian  items
    {
        name: 'Penne Alfredo',
        description: 'Creamy white sauce pasta with garlic, herbs, and parmesan.',
        category: 'italian',
        price: 329,
        rating: 4.5,
        hearts: 85,
        total: 329,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTL2xP20vJ2CLrsJ28i1qeaiO6N6dElC3Gr0Q&s',
    },
    {
        name: 'Veggie Delight Pizza',
        description: 'Loaded pizza with olives, capsicum, corn, and mozzarella cheese.',
        category: 'italian',
        price: 379,
        rating: 4.4,
        hearts: 90,
        total: 379,
        imageUrl: 'https://m1.quebecormedia.com/emp/cl_prod/canadian_living-_-defbc3c3683d28a2df0fe124203f039c37678bb9-_-veggie-delight-pizza.jpg?impolicy=resize&width=1500&height=1500',
    },
    {
        name: 'Cheese Garlic Bread',
        description: 'Crispy bread topped with garlic butter and melted cheese.',
        category: 'italian',
        price: 219,
        rating: 4.3,
        hearts: 70,
        total: 219,
        imageUrl: 'https://www.vegrecipesofindia.com/wp-content/uploads/2015/07/cheese-garlic-bread-recipe-1.jpg',
    },
    {
        name: 'Spaghetti Pomodoro',
        description: 'Classic spaghetti tossed in fresh tomato basil sauce.',
        category: 'italian',
        price: 299,
        rating: 3.0,
        hearts: 78,
        total: 299,
        imageUrl: 'https://assets.tmecosys.cn/image/upload/t_web_rdp_recipe_584x480/img/recipe/ras/Assets/80a796dd-e463-447f-a459-7ba776f0c746/Derivates/9d0824cf-968a-4bf6-a0bd-e86edb42c52a.jpg',
    },
    {
        name: 'Four Cheese Pizza',
        description: 'Pizza topped with mozzarella, cheddar, parmesan, and blue cheese.',
        category: 'italian',
        price: 429,
        rating: 4.6,
        hearts: 105,
        total: 429,
        imageUrl: 'https://static.toiimg.com/photo/59123476.cms',
    },
    {
        name: 'Creamy Mushroom Pasta',
        description: 'Pasta cooked in creamy mushroom sauce with herbs.',
        category: 'italian',
        price: 349,
        rating: 4.5,
        hearts: 88,
        total: 349,
        imageUrl: 'https://www.glitterandgraze.com/wp-content/uploads/2017/02/Untitled-design-50_auto_x2-500x500.jpg',
    },
    {
        name: 'Italian Veg Calzone',
        description: 'Folded pizza stuffed with veggies, cheese, and herbs.',
        category: 'italian',
        price: 359,
        rating: 3.4,
        hearts: 82,
        total: 359,
        imageUrl: 'https://www.sargento.com/assets/Uploads/Recipe/Image/veggiecalzone__FocusFillWyIwLjAwIiwiMC4wMCIsODAwLDQ3OF0_CompressedW10.jpg',
    },

    // desserts items


    {
        name: 'Strawberry Cheesecake Jar',
        description: 'Layered strawberry cheesecake in a jar with crunchy base.',
        category: 'desserts',
        price: 189,
        rating: 4.7,
        hearts: 0,
        total: 189,
        imageUrl: 'https://www.bakkemaison.com/wp-content/uploads/2023/06/BM226-1-1.jpg',
    },
    {
        name: 'Chocolate Truffle Bite',
        description: 'Soft chocolate truffle bites with cocoa dust.',
        category: 'desserts',
        price: 149,
        rating: 4.5,
        hearts: 0,
        total: 149,
        imageUrl: 'https://nt.global.ssl.fastly.net/binaries/content/gallery/website/national/library/discover-and-learn/food-recipes/chocolate-brownie-truffle-bites-1538487.jpg',
    },
   
];

/**
 * Optional extra veg-only items to make each category feel full in UI.
 * Keep names simple + unique. Set EXTRA_MENU_PER_CATEGORY in .env to enable.
 */

const extraCategories = [
    { key: 'breakfast', label: 'Breakfast', basePrice: 129, step: 7 },
    { key: 'lunch', label: 'Lunch', basePrice: 219, step: 9 },
    { key: 'dinner', label: 'Dinner', basePrice: 269, step: 11 },
    { key: 'mexican', label: 'Mexican', basePrice: 179, step: 10 },
    { key: 'italian', label: 'Italian', basePrice: 239, step: 8 },
    { key: 'desserts', label: 'Desserts', basePrice: 119, step: 6 },
    { key: 'drinks', label: 'Drinks', basePrice: 89, step: 5 },
];

const extraPerCategory = Number(process.env.EXTRA_MENU_PER_CATEGORY || 0);

if (extraPerCategory > 0) {
    for (const cat of extraCategories) {
        const existingCount = menuItems.filter((m) => m.category === cat.key).length;
        for (let i = 1; i <= extraPerCategory; i++) {
        const price = cat.basePrice + (i * cat.step) % 180;
        const rating = 4.1 + (i % 8) * 0.1;
        const serial = existingCount + i;
            menuItems.push({
                name: `${cat.label} Veg Delight ${serial}`,
                description: `Fresh vegetarian delight with seasonal flavours. Simple, tasty, and perfect for today.`,
                category: cat.key,
                price,
                rating: Number(rating.toFixed(1)),
                hearts: 0,
                total: price,
                imageUrl: '',
            });
        }
    }
}

/** Schema mein name unique hai — seed file mein jo naam do baar ho unhe (2), (3)… karke insert karein */
function withUniqueNames(entries) {
    const used = new Set();
    return entries.map((doc) => {
        const base = String(doc.name || '').trim() || 'Unnamed item';
        let name = base;
        if (!used.has(name)) {
            used.add(name);
            return { ...doc, name, total: Number(doc.price) };
        }
        let n = 2;
        while (used.has(`${base} (${n})`)) n += 1;
        name = `${base} (${n})`;
        console.warn(`Duplicate name: "${base}" → "${name}"`);
        used.add(name);
        return { ...doc, name, total: Number(doc.price) };
    });
}

async function seed() {
    await mongoose.connect(MONGO_URI);
    console.log('Connected. Replacing menu data from seed file…');
    const wipe = await Item.deleteMany({});
    if (wipe.deletedCount) console.log(`Deleted ${wipe.deletedCount} existing items.`);

    console.log('Removing retired non-veg items…');
    const del = await Item.deleteMany({ name: { $in: retiredNames } });
    if (del.deletedCount) console.log(`Deleted ${del.deletedCount} old items.`);

    console.log('Seeding vegetarian menu…');
    const docs = withUniqueNames(menuItems);
    await Item.insertMany(docs, { ordered: false });
    const inDb = await Item.countDocuments();
    console.log(
        `Done. File mein ${docs.length} items; DB mein ab total ${inDb} items (${[...new Set(menuItems.map((m) => m.category))].join(', ')}).`,
    );
    await mongoose.disconnect();
}

seed().catch((e) => {
    console.error(e);
    process.exit(1);
});
